packages:
  - .

overrides:
  '@hono/node-server': 1.19.13
  postcss: 8.5.14

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
