name: Build & Push

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Push Docker GCR
        - uses: actions/checkout@v2
        - uses: google-github-actions/setup-gcloud@master
        - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          registry: gcr.io
          image_name: vestaboard-local
          image_tag: latest
          dockerfile: ./Dockerfile
