name: Build & Push

on:
  push:
    branches: [master]

jobs:
  # amd:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
  #       with:
  #         username: ${{ secrets.DOCKER_USER }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
  #       with:
  #         images: bucatini/vbcontroller
  #         tags: |
  #           type=sha,prefix=amd-,format=short
  #           type=raw,value=amd-latest

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
  #       with:
  #         context: .
  #         push: true
  #         platforms: linux/amd64
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}

  arm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: pguyot/arm-runner-action@v2
        name: Setup raspbian
        with:
          base_image: raspios_lite_arm64:latest
          commands: |
            docker ps

      # - name: Compress the release image
      #   run: |
      #     mv ${{ steps.build_image.outputs.image }} my-release-image.img
      #     xz -0 -T 0 -v my-release-image.img

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
      #   with:
      #     images: bucatini/vbcontroller
      #     tags: |
      #       type=sha,prefix=pi-,format=short
      #       type=raw,value=pi-latest

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/arm64
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
