name: Frontend

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        working-directory: ./vb-settings
        run: pnpm i

      - name: Lint
        working-directory: ./vb-settings
        run: pnpm run lint

      - name: Audit
        working-directory: ./vb-settings
        run: |
          pnpm audit --audit-level high --json > audit_results.json
          node scripts/ci/report-vulns.js $(readlink -f audit_results.json)
