name: Frontend

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install dependencies
        working-directory: ./vb-settings
        run: pnpm install --frozen-lockfile

      - name: Lint
        working-directory: ./vb-settings
        run: pnpm run lint

      - name: Audit
        working-directory: ./vb-settings
        run: |
          pnpm audit --audit-level high --json > audit_results.json
          node scripts/ci/report-vulns.mjs $(readlink -f audit_results.json)
